Added missing check

diff --git a/maint/fetch.in b/maint/fetch.in
--- a/maint/fetch.in
+++ b/maint/fetch.in
@@ -56,6 +56,11 @@ if test "$WGET" = "" ; then
     echo "$me: Missing wget executable ..."
     exit 1
 fi
+if test "$WGET" = "@WGET@" ; then
+    echo "$me: Missing wget autoconf substitution ..."
+    exit 1
+fi
+
 if test "$URL" = "" ; then
     echo "$me: Missing input URL"
     echo "Try \`$program --help' for more information."
